<?php

namespace Simplon\ActivitePartageBundle\Repository;

/**
 * DonsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonsRepository extends \Doctrine\ORM\EntityRepository
{
}
