<?php

namespace Simplon\ActivitePartageBundle\Repository;

/**
 * StatutDonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutDonRepository extends \Doctrine\ORM\EntityRepository
{
}
